### ISSUE TITLE
installation trouble: "augment" not exported from modelgenerics?

### ISSUE THREAD

**Issue by bbolker** [alexpghayes/modeltests#14]
I tried this:

```
devtools::install_github("alexpghayes/modelgenerics")
devtools::install_github("alexpghayes/modeltests")
```

First call works, but second fails with

> Error : object ‘augment’ is not exported by 'namespace:modelgenerics'

Am I missing something obvious?  (R version "(2018-07-26 r75007)", x86_64-pc-linux-gnu)

**Comment by alexpghayes** [comment]
`topepo/modelgenerics` got moved to `r-lib/generics`. I've been away for a while and haven't fixed the breakages this caused. Thanks for pointing this out, working on it now.

**Comment by alexpghayes** [comment]
Give `remotes::install_github("alexpghayes/modeltests")` a go for me? It should install `r-lib/generics` for you by default.

Still need to update the development version of `broom`.

**Comment by bbolker** [comment]
works for me.
