### ISSUE TITLE
Final release checks

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/modeltests#31]
cc @simonpcouch 

- [x] Passes R CMD check locallly on my laptop
- [x] `check_rhub()`
- [x] `check_win_*()`

I'll tag you again once I get the results, at which point I'll also submit. Also, please feel free to add yourself as an author or contributor!

**Comment by simonpcouch** [comment]
Sounds good! Just added myself to DESCRIPTION as a contributor.

**Comment by alexpghayes** [comment]
Submitted to CRAN! Thanks!
