### ISSUE TITLE
possible release ahead of upcoming broom release

### ISSUE THREAD

**Issue by simonpcouch** [alexpghayes/modeltests#39]
Hey Alex! Hope you're taking care.

I'm looking towards sending out a broom release in the coming weeks to handle a [breakage in the survival tidiers](https://github.com/tidymodels/broom/issues/1195). I'd like to also include the changes from tidymodels/broom#1191, which would be best-tested with the changes from #38 in this repo. Would you be game to send out a modeltests release sometime soon?

**Comment by alexpghayes** [comment]
Can do! Please ping me if I haven't made moves on this by Friday.

Also, modeltests is sort of a weird repo/idea that never got fully fleshed out, but happy to transfer the repo or maintainership of the package to make `broom` maintenance easier.

**Comment by simonpcouch** [comment]
Much appreciated!

Let me know if being maintainer feels unwanted / high-friction for you and we can figure something out. Given where broom is at in its lifecycle, I'm fine to coast as-is, but also game to take over or write out the dependency if that'd feel better for you.

**Comment by simonpcouch** [comment]
Pinging. :)

**Comment by alexpghayes** [comment]
Underway!
