### ISSUE TITLE
New Column Name Request

### ISSUE THREAD

**Issue by emstruong** [alexpghayes/modeltests#41]
Following https://www.tidymodels.org/learn/develop/broom/#glossaries ,

I'd like to request the column name "construct.type" to be added. The cSEM package models both common factors (latent variables) and composite variables. 

Unlike lavaan, whether a construct is a common factor or composite variable cannot be inferred by the operation (`op`) associated between the indicators and its construct in cSEM due to the nature of the statistical methods.

**Comment by alexpghayes** [comment]
Would this be to support tidiers in `cSEM`?

**Comment by emstruong** [comment]
> Would this be to support tidiers in `cSEM`?

Yes, although I ended up using the `type` column name instead. Is that okay?

**Comment by alexpghayes** [comment]
Yeah, that's fine! Do you still need me to make a change if you use `type`?

**Comment by emstruong** [comment]
> Yeah, that's fine! Do you still need me to make a change if you use `type`?

No, thank you! I don't anticipate needing construct.type anymore. :)
